# Generated by Django 5.0.3 on 2024-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('g', 'g'), ('beton', 'beton')], default='beton', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
