# Generated by Django 5.0.3 on 2024-03-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='prod',
        ),
    ]
