# Generated by Django 5.0.3 on 2024-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_description_product_group_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуга'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
