# Generated by Django 5.0.3 on 2024-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_note_comment_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('rent', 'rent'), ('buy', 'buy')], max_length=20, null=True),
        ),
    ]
