# Generated by Django 5.0.3 on 2024-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options_remove_product_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], max_length=20, null=True),
        ),
    ]
